name: Bug Report
description: "For reporting bugs"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        <br><br>
        Please make sure you have done the following:
        
        - Have you checked if the mod is on the latest version, the latest version can be found [here](https://modrinth.com/mod/warputils/versions)\
        - Please also check if the issue has already been reported
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: >-
        Describe the isse in as much detail as possible. This section should contain what behaviour expect and why you believe the actual behaviour is a bug. If this issue only occurs with specific mods installed, provide their names and versions.

        **Hint:** If you have any additional information, such as screenshots or videos, that you feel would help explain the issue, please attach them here.
  - type: textarea
    id: description-reproduction-steps
    attributes:
      label: Reproduction Steps
      description: >-
        Please provide detailed instructions on how to reproduce the bug. Make sure your instructions are clear and concise, as other people will need to follow them to recreate the issue.
        
        **Hint:**  A common way to fill this section out is to write a step-by-step guide.
    validations:
      required: true
  - type: textarea
    id: log-file
    attributes:
      label: Log File
      description: >-
        **Hint:** You can usually find the log files within the folder `.minecraft/logs`. Most often, you will want the `latest.log`
        file, since that file belongs to the last played session of the game.
      placeholder: >-
        Drag-and-drop the log file here.
    validations:
      required: true
  - type: textarea
    id: crash-report-file
    attributes:
      label: Crash Report
      description: >-
        **Important:** Even if your game is _not crashing_ as a result of your problem, we still need a crash report. This
        file contains important information about your hardware and software configuration. You can generate a crash report
        manually by loading the game to the main menu, and holding the F3+C keys together for approximately 10 seconds.
        
        **Hint:** You can usually find crash reports (with their date and time) in the folder `.minecraft/crash-reports`.
      placeholder: >-
        Drag-and-drop the crash report file here.
    validations:
      required: true
